#!/bin/sh
cat <<'EOF'
┏┓    •      ┳┳┓      •          
┃┃┏┓┏┓┓┏┓┏╋  ┃┃┃┏┓┏┓┏┓┓┏┓┏┓┏╋┏┓┏┓
┣┛┛ ┗┛┃┗ ┗┗  ┛ ┗┗┛┛ ┛┗┗┛┗┗┫┛┗┗┻┛ 
      ┛                   ┛      
EOF

HOSTNAME=$(hostname)
[ -r /etc/lsb-release ] && . /etc/lsb-release

echo "+----------------------------------------+"
printf "| %-38s |\n" "Hostname: $HOSTNAME"
printf "| %-38s |\n" "OS: $DISTRIB_DESCRIPTION"
echo "+----------------------------------------+"